spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/rest
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath*:schema.sql
      mode: always
  cloud:
    stream:
      bindings:
        order-out-0: 
          destination: orderToDeliver

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/